### ISSUE TITLE
querymany fails with 'HTTPError: 400 Client Error: Expect type list. for url: http://mygene.info/v3/query/'

### ISSUE THREAD

**Issue by RaverJay** [biothings/mygene.py#16]
Hi there,

querymany fails with:

```
Traceback (most recent call last):
  File "/home/ya86gul/scripts/geneid_conversion.py", line 90, in <module>
    reports = query_mygene(gids, species=species)
  File "/home/ya86gul/scripts/geneid_conversion.py", line 61, in query_mygene
    ret = mg.querymany(gids, verbose=False, scopes=scopes, species=species, fields=['_id', '_score', 'entrezgene', 'name', 'symbol', 'taxid', 'type_of_gene', 'summary', 'pathway'])
  File "/home/ya86gul/miniconda3/lib/python3.7/site-packages/biothings_client/base.py", line 542, in _querymany
    for hits in self._repeated_query(query_fn, qterms, verbose=verbose):
  File "/home/ya86gul/miniconda3/lib/python3.7/site-packages/biothings_client/base.py", line 223, in _repeated_query
    from_cache, query_result = query_fn(batch, **fn_kwargs)
  File "/home/ya86gul/miniconda3/lib/python3.7/site-packages/biothings_client/base.py", line 541, in query_fn
    def query_fn(qterms): return self._querymany_inner(qterms, verbose=verbose, **kwargs)
  File "/home/ya86gul/miniconda3/lib/python3.7/site-packages/biothings_client/base.py", line 488, in _querymany_inner
    return self._post(_url, params=_kwargs, verbose=verbose)
  File "/home/ya86gul/miniconda3/lib/python3.7/site-packages/biothings_client/base.py", line 176, in _post
    res.raise_for_status()
  File "/home/ya86gul/miniconda3/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Expect type list. for url: http://mygene.info/v3/query/
```

code:
```
mg = mygene.MyGeneInfo()
    ret = mg.querymany(gids, verbose=False, scopes=scopes, species=species, fields=['_id', '_score', 'entrezgene', 'name', 'symbol', 'taxid', 'type_of_gene', 'summary', 'pathway'])
```
where gids is a list of Ensembl ids, e.g. `['ENSG00000228903', 'ENSG00000185031', 'ENSG00000250266', ...]`

This worked fine a week ago. I tried updating to 3.2.0 from 3.1.0 but did not help.

Ideas?

**Comment by namespacestd0** [comment]
I am not able to replicate the error. Can you share the result of `pip list` and the exact query arguments you used?

**Comment by newgene** [comment]
@RaverJay My guess is this should resolve the issue (`mygene` pacakage depends on `biothings_client` package:

```
pip install biothings_client -U
```

**Comment by newgene** [comment]
@RaverJay We just released a new version of "mygene" (v3.2.1) to use the latest biothings_client dependency. Can you please double-check if this issue has been resolved by doing:

```
pip install mygene -U
```

Ref: 
- https://pypi.org/project/mygene/
- https://pypi.org/project/biothings-client/

**Comment by newgene** [comment]
Also ref to the relevant issue from biothings_client: https://github.com/biothings/biothings_client.py/issues/17

**Comment by RaverJay** [comment]
Sorry I didn't mention before, I use conda for managing my packages.

An old environment works, it has:
```
# Name                    Version                   Build  Channel
biothings_client          0.2.1                      py_0    bioconda
mygene                    3.1.0                      py_0    bioconda
```

The failing environment has:
```
# Name                    Version                   Build  Channel
biothings_client          0.2.3              pyh3252c3a_0    bioconda
mygene                    3.2.0              pyh3252c3a_0    bioconda
```

Updating to newest biothings_client=0.2.4 solved the issue.

**Comment by newgene** [comment]
@RaverJay got it. This is indeed an issue introduced in `biothings_client==0.2.3`, which became an issue when we introduced stringent input parameter checks in a recent MyGene.info API release.

I also noticed both `mygene` and `biothings_client` packages in bioconda have shown our latest releases now:

https://anaconda.org/bioconda/biothings_client
https://anaconda.org/bioconda/mygene
