### ISSUE TITLE
500 Server Error: N/A for url: http://mygene.info/v3/query/

### ISSUE THREAD

**Issue by sarah-n-wright** [biothings/mygene.py#22]
I am getting the following error message on the majority of my requests, which I am making via mygene v3.2.2. However, this error is not consistently returned for the same query. Is this a problem with the package, or a problem with the server?

```
Traceback (most recent call last):   
   File "<string>", line 1, in <module>    
   File "/lib/python3.10/site-packages/biothings_client/base.py", line 552, in _querymany   
        for hits in self._repeated_query(query_fn, qterms, verbose=verbose):   
   File "lib/python3.10/site-packages/biothings_client/base.py", line 233, in _repeated_query   
        from_cache, query_result = query_fn(batch, **fn_kwargs)  
   File "lib/python3.10/site-packages/biothings_client/base.py", line 551, in query_fn
        def query_fn(qterms): return self._querymany_inner(qterms, verbose=verbose, **kwargs)   
   File "python3.10/site-packages/biothings_client/base.py", line 499, in _querymany_inner   
        return self._post(_url, params=_kwargs, verbose=verbose)   
    File "/lib/python3.10/site-packages/biothings_client/base.py", line 179, in _post   
        res.raise_for_status()  
    File "/lib/python3.10/site-packages/requests/models.py", line 953, in raise_for_status   
        raise HTTPError(http_error_msg, response=self)   
   requests.exceptions.HTTPError: 500 Server Error: N/A for url: http://mygene.info/v3/query/
```

For example, the following query is sometimes successful and sometimes returns the error:
```
mg.querymany(qterms=["HIST1H4A", "ATP5G2", "BRAF"], scopes=scopes, fields=fields, species='human')
```
Successful response:
```
querying 1-3...done.  
Finished.  
1 input query terms found dup hits:  
	[('BRAF', 3)]  
2 input query terms found no hit:	
        ['HIST1H4A', 'ATP5G2']  
Pass "returnall=True" to return complete lists of duplicate or missing query terms.
```

**Comment by newgene** [comment]
@sarah-n-wright thanks for letting us know. Looks like our API server was getting a large number of requests in recent hours, some user requests were then rejected by the server with the 500 server errors you saw. 

This usage spike is over now, so you should be able to use our API again. We are also investigating the details of this incident to see if anything we need to do on our end (scaling up or adjusting throttling from the single users etc).

Closing this issue for now, but definitely let us know if you still see any issue.
